### PR TITLE
update dep libs, fixes jsonpatch bugs

### PR DESCRIPTION
**Pull request by boypt**
- update all js deps
- fixes: github.com/mattbaird/jsonpatch has bugs on calculation array ops, and the repo is unmaintained for years, another fork (gomodules.xyz/jsonpatch) keep it maintained and which fixes the bug too

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks though can we use the github domain instead of the xyz domain? I can
trust GitHub to exist in 5 years, not to sure about this other one. GOPROXY
kind of solves this though still would prefer GH 👍

**Comment by boypt** [comment]
Oh I'm not the owner of "gomodules.xyz" domain.
I understand you concern, maybe we can use the vendor solution, include the repo in the vendor dir.

**Comment by jpillora** [comment]
Oh sorry we don’t need to vendor

Should be able to use  https://github.com/gomodules/jsonpatch

**Comment by jpillora** [comment]
Manually merging this 👍

**Comment by jpillora** [comment]
squash merged in a972b3f, ended up keeping "gomodules.xyz" its aliased to use this domain

**Pull request closed without merging**
